databases:
  - name: church-db
    plan: free
    databaseName: church
    user: church

services:
  - type: web
    name: church-management-system
    env: docker
    rootDirectory: .
    region: oregon
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: church-db
          property: connectionString
    autoDeploy: true
    healthCheckPath: /health
